#!/bin/bash

MYPWD=${PWD}

echo 'Create .env file'
cp .env.example .env

cd laradock*

cp .env-example .env
echo "cp .env"

cp nginx/Dockerfile.example nginx/Dockerfile
cp nginx/sites/default.conf.example nginx/sites/default.conf
echo "cp nginx conf"

docker-compose up -d nginx php-fpm mysql workspace phpmyadmin php-worker

docker-compose exec workspace bash -e ./install/php-install
docker-compose exec workspace bash -e ./install/keychmod-install

npm install
