#!/bin/bash
cd laradockAdmin
docker-compose up -d nginx php-fpm mysql workspace phpmyadmin php-worker

docker-compose exec workspace bash -e ./install/php-install
docker-compose exec workspace bash -e ./install/keychmod-install

npm install
