#!/bin/bash

chmod 777 -R ./bootstrap
echo 'Set chmod 777 for /bootstrap ok/ '

chmod 777 -R ./storage
echo 'Set chmod 777 for /storage ok/ '

chmod 777 -R ./storage/logs
echo 'Set chmod 777 for /storage/logs ok/ '

file="./storage/logs/error.log"
if [[ ! -f $file ]]; then
  touch $file
fi

file="./storage/logs/info.log"
if [[ ! -f $file ]]; then
  touch $file
fi

chmod 777 ./storage/logs/error.log
echo 'Set chmod 777 for /storage/logs/error.log ok/ '

chmod 777 ./storage/logs/info.log
echo 'Set chmod 777 for /storage/logs/info.log ok/ '

mkdir -p ./storage/app/files/images/backend_images/large
mkdir -p ./storage/app/files/images/backend_images/medium
mkdir -p ./storage/app/files/images/backend_images/small

mkdir -p ./storage/app/files/images/carsGallery/large
mkdir -p ./storage/app/files/images/carsGallery/medium
mkdir -p ./storage/app/files/images/carsGallery/small

chmod 777 -R ./storage/app/files

cd ./public

ln -sf ../storage/app/files files

chmod 777 files

exit

